# First param ─┌
[username]
format = " [╭─$user]($style)@"
style_user = "bold red"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style)"
style = "bold dimmed red"
trim_at = "-"
ssh_only = false
disabled = false

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false


## SECOND LINE/ROW: Prompt
# Somethere at the beginning

# Prompt: param 2 └─
[character]
success_symbol = " [╰─>](bold red)"
error_symbol = " [╰─>](bold red)"
