theme = "vim_dark_high_contrast"

[editor]
true-color = true
line-number = "relative"
rulers = [80]
text-width = 79
auto-pairs = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
# space = "·"
space = " "
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.file-picker]
parents = false

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-at-text-width = true

[editor.smart-tab]
enable = false
